name: trigger_dev_production
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/trigger_dev_production.yml
      - frontend/internal-packages/jobs/**
      - frontend/packages/db-structure/**
      - frontend/packages/github/**
      - frontend/internal-packages/db/**
      - frontend/internal-packages/agent/**
      - turbo.json

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  trigger_dev:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: ./.github/actions/pnpm-setup

      - name: Deploy to trigger.dev production
        shell: bash
        env:
          TRIGGER_ACCESS_TOKEN: ${{ secrets.TRIGGER_ACCESS_TOKEN }}
          TRIGGER_PROJECT_ID: ${{ vars.TRIGGER_PROJECT_ID }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          NEXT_PUBLIC_ENV_NAME: production
        run: pnpm deploy:jobs

      - name: Slack Notification on Failure
        if: failure()
        uses: tokorom/action-slack-incoming-webhook@d57bf1eb618f3dae9509afefa70d5774ad3d42bf # v1.3.0
        env:
          INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_CLI_CI_WEBHOOK_URL }}
        with:
          text: "Deploy to trigger.dev production Failure"
          attachments: |
            [
              {
                "color": "bad",
                "fields": [
                  {
                    "title": "Result",
                    "value": "failure"
                  },
                  {
                    "title": "Job URL",
                    "value": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                  }
                ]
              }
            ]
